FROM node:argon

# npm install and copy dependencies
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /app && cp -a /tmp/node_modules /app

# copy app files
WORKDIR /app
ADD . /app

# need to install bcrypt again because OSX compiled bcrypt doesn't work on Linux
RUN npm install bcrypt
RUN npm install webpack -g
RUN webpack -d

EXPOSE 3000
CMD ["npm", "start"]
